# Generated by Django 4.1.2 on 2022-10-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBlog', '0003_post_post_date_alter_post_title_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='date_post',
        ),
    ]
