# Generated by Django 4.1.2 on 2022-10-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBlog', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Abre o post para ler o artigo', max_length=255),
        ),
    ]
