# Generated by Django 4.1.2 on 2022-10-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBlog', '0008_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(max_length=255),
        ),
    ]
